config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts
  resources :comments
  resources :trashes
  get '/posts/move_to_trash/:id', controller:  :posts, action: :move_to_trash, as: :trash_post
  get '/comments/move_to_trash/:id', controller:  :comments, action: :move_to_trash, as: :trash_comment
  get '/trashes/restore_posts/:id',controller: :trashes,action: :restore_post,
      as: :restore_post
  get '/trashes/restore_comment/:id',controller: :trashes,action: :restore_comment,
      as: :restore_comment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates_presence_of :title,:content

  def active_comments
    comments.where(thrashed:false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :fetch_comment, only:[:move_to_trash,:destroy,:edit,:update]

  def create
    @comment = Comment.create!(comment_params)
    @modal_action = "close"
    respond_to do |format|
      format.js {render 'update_comment_listing'}
    end
  end

  def move_to_trash
    SafeDelete.new(@comment).call
    @modal_action = "close"
    respond_to do |format|
      format.js {render 'update_comment_listing'}
    end
  end

  def destroy
    @comment.destroy
    @modal_action = "close"
    respond_to do |format|
      format.js {render 'update_comment_listing'}
    end
  end

  def edit
    @modal_action ="open"
    respond_to do |format|
      format.js {render 'update_comment_listing'}
    end
  end

  def update
    @comment.update(comment_params)
    @modal_action = "close"
    respond_to do |format|
      format.js {render 'update_comment_listing'}
    end
  end

  private

  def fetch_comment
    @comment =  Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content,:thrashed,:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :fetch_post, only:[:move_to_trash,:destroy,:edit,:update]
  before_action :fetch_posts, only:[:index,:new,:edit]
  after_action :fetch_posts, only: [:update]
  before_action :new_comment

  def index
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.js {render 'update_post_listing'}
    end
  end

  def edit
    respond_to do |format|
      format.js {render 'update_post_listing'}
    end
  end

  def create
    Post.create!(post_params)
    @modal_action = "close"
    @posts = Post.where(thrashed:false)
    respond_to do |format|
      format.js {render 'update_post_listing'}
    end
  end

  def update
    @post.update(post_params)
    @modal_action ="close"
    @posts = Post.where(thrashed:false)
    respond_to do |format|
      format.js {render 'update_post_listing'}
    end
  end

  def move_to_trash
    SafeDelete.new(@post).call
    @modal_action = "close"
    @posts = Post.where(thrashed:false)
    respond_to do |format|
      format.js{render 'posts/update_post_listing'}
    end
  end

  def destroy
    @modal_action = "close"
    @post.destroy!
    @posts = Post.where(thrashed:false)
    respond_to do |format|
      format.js {render 'posts/update_post_listing'}
    end

  end

  private
  def fetch_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:content,:thrashed)
  end

  def fetch_posts
    @posts = Post.where(thrashed:false)
  end

  def new_comment
    @comment = Comment.new
  end
end

app/controllers/trashes_controller.rb
class TrashesController < ApplicationController
  before_action :fetch_post, only:[:restore_post]
  before_action :fetch_comment, only:[:restore_comment]
  def index
    @posts =  Post.where(thrashed:true)
    # Fetching comments for which posts are not trashed but comments are trashed
    active_posts = Post.where(thrashed:false)
    comment_ids = []
    active_posts.each do |post|
      comment_ids.concat (post.comments.where(thrashed:true).pluck(:id))
    end
    @comments = Comment.where(id:comment_ids)
  end

  def restore_post
    Restore.new(@post).call
    redirect_to trashes_path
  end

  def restore_comment
    Restore.new(@comment).call
    redirect_to trashes_path
  end

  private
  def fetch_post
    @post =  Post.find(params[:id])
  end
  def fetch_comment
    @comment =  Comment.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/trashes_helper.rb
module TrashesHelper
end

app/views/application/_top_nav.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <%=link_to "SafeDelete",posts_path,class:"nav-link",style:"color:white" %>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%=link_to "Home",posts_path,class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%=link_to "Trash",trashes_path,class:"nav-link" %>
    <li class="nav-item">
  </ul>
</nav>

app/views/comments/_comment_form.html.erb
<%= form_for comment, remote:true do |f| %>
  <div class ="form-group">
    <label class ="label">Add Comment</label>
    <%=f.text_area :content,class:"form-control" %>
  </div>
  <%= f.hidden_field :thrashed,value:false %>
  <%= f.hidden_field :post_id,value:post_id %>
  <%=f.submit "Save",class:"btn btn-primary" %>
<% end %>

app/views/comments/_comment_listing.html.erb
<%post.active_comments.each do |comment| %>
  <div class ="comment-content">
    <p><%= comment.content %></p>
    <%= link_to "destroy", trash_comment_path(comment.id),remote:true %>
    <%=link_to "delete", comment_path(comment.id),method: :delete,remote:true %>
    <%=link_to "edit", edit_comment_path(comment.id), remote: true %>
    <hr>
  </div>
<%end %>

app/views/comments/_comment_modal.html.erb
<div class="modal" id="comment-modal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                Create/Edit Comment
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div id="comment-form-area">

                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

app/views/comments/update_comment_listing.js.erb
$('#comments-of-<%=@comment.post.id%>').html('<%=escape_javascript render 'comment_listing', post:@comment.post %>')
<%if @modal_action == "close" %>
   $('#comment-modal').modal('hide');
<%else %>
  $('#comment-form-area').html('<%=escape_javascript render 'comment_form',comment:@comment,post_id:@comment.post.id %>')
  $('#comment-modal').modal('show');
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithSafeDelete</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'application/top_nav' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_listing.html.erb
<% unless posts.blank? %>
  <%posts.each do |post| %>
    <div class ="post-container">
      <div class ="post-title col-md-6">
        <p><b>Title:</b><%=post.title%></p>
      </div>
      <div class = "post-content col-md-8">
        <p><b>Content:</b></b><%= post.content %></p>
      </div>
      <div class ="action-links col-md-8">
        <%=link_to "destroy_post", trash_post_path(post.id),remote:true,class:"link-item" %>
        <%=link_to "delete_post", post_path(post.id),method: :delete, remote:true,class:"link-item" %>
        <%=link_to "edit_post", edit_post_path(post.id),remote: true,class:"link-item" %>
      </div>
      <div class ="comments-section">
        <div class ="section-header col-md-6"><b>Comments</b></div>
        <div class ="comment-form-section col-md-8">
          <%= render 'comments/comment_form', comment:@comment, post_id:post.id %>
          <hr>
        </div>
        <div class = "comments-container" id="comments-of-<%=post.id%>">
          <div class ="comment-listing-area col-md-8">
            <%= render 'comments/comment_listing', post:post %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>

app/views/posts/_post_form.html.erb
<%= form_for post, remote: true do |f|%>
  <div class ="form-group">
    <label class="label">Title</label>
    <%=f.text_field :title,class:"form-control" %>
  </div>
  <div class ="form-group">
    <label class ="label">Content</label>
    <%= f.text_area :content,class:"form-control" %>
  </div>
  <%= f.hidden_field :thrashed,value:false %>
  <%=f.submit "Submit",class:"btn btn-primary" %>
<%end %>

app/views/posts/_post_modal.html.erb
<div class="modal" id="postModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        Create/Edit Post
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div id="postFormArea">

        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class ="container">

    <div class = "section-header row">
      <div class="heading-text col-md-6">
        Posts Listing
      </div>
      <div class="col-md-6">
          <%=link_to "New Post",new_post_path,class:"btn btn-primary float-right",remote:
              true %>
      </div>
    </div>
    <div id= "post-listing-section" class ="margin-top-">
      <%= render 'listing',posts:@posts,comment:@comment %>
    </div>
  <%=render 'post_modal' %>
  <%=render 'comments/comment_modal' %>
</div>

app/views/posts/update_post_listing.js.erb
  $('#post-listing-section').html('<%=escape_javascript render 'posts/listing',posts:@posts %>')
  <%if @modal_action == "close" %>
    $('#postModal').modal('hide');
  <% else %>
    $('#postFormArea').html('<%=escape_javascript render 'posts/post_form', post:@post %>')
   $('#postModal').modal('show');
  <% end %>

app/views/trashes/index.html.erb
<div class ="container">
     <h3>Posts</h3>
-    <div id="posts">
      <% unless @posts.blank?%>
        <%@posts.each do |post| %>
          <div class ="post-title">
            <%=post.title %><%=link_to "Restore",restore_post_path(post.id)%>
          </div>
        <% end %>
      <% end %>
    </div>
    <h3>Comments</h3>
    <div id="comments">
      <% unless @comments.blank? %>
        <%@comments.each do |comment| %>
          <div class ="comment-content">
            <p><%= comment.content %></p>
            Post Title:<%=comment.post.title%><%=link_to "Restore",restore_comment_path(comment.id) %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>